version: '3.8'

services:
  CadNutriDB:
    image: postgres:16
    container_name: CadNutriDB
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: CadNutriDB
    ports:
      - "5431:5432"
    volumes:
      - CadNutriDATA:/var/lib/postgresql/data
    networks:
      - cadnutri_net

  CadNutriSubModule:
    build: ./CadNutriSubModule
    image: orquestradorcadnutri-cadnutrisubmodule
    container_name: CadNutriApp
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      URL_REDIRECTS: http://CadNutriSubModule:80
      DB_HOST: CadNutriDB
    depends_on:
      - CadNutriDB
    networks:
      - cadnutri_net

  CadNutriSubModuleAltura:
    build: ./CadNutriSubModuleAltura
    image: orquestradorcadnutri-cadnutrisubmodulealtura
    container_name: CadNutriAppAltura
    restart: unless-stopped
    ports:
      - "5001:5000" 
    networks:
      - cadnutri_net

volumes:
  CadNutriDATA:

networks:
  cadnutri_net:
    driver: bridge