version: '3.8'
services:
  CadNutriDB:
    image: postgres:16
    container_name: CadNutriDB
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: CadNutriDB
    ports:
      - "5431:5432"
    volumes:
      - CadNutriDATA:/var/lib/postgresql/data

  CadNutriSubModule:
    build: ./CadNutriSubModule
    container_name: CadNutriApp
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      URL_REDIRECTS: http://CadNutriSubModule:80
    depends_on:
      - CadNutriDB

volumes:
  CadNutriDATA: